apiVersion: v1
kind: Service
metadata:
  name: film-cube-app-service
  namespace: filmcube
spec:
  selector:
    app: film-cube-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
