apiVersion: apps/v1
kind: Deployment
metadata:
  name: film-cube-app
  namespace: filmcube
  labels:
    app: film-cube-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: film-cube-app
  template:
    metadata:
      labels:
        app: film-cube-app
    spec:
      containers:
        - name: film-cube-app
          image: chaitanyamunje08/film-cube-application:1.3
          ports:
            - containerPort: 80
